
import { Movie } from '../types';

const mockMovies: Movie[] = [
  {
    id: 1,
    title: "Cosmic Dreamer",
    posterUrl: "https://picsum.photos/seed/cosmic/500/750",
    description: "In a distant future, a young woman discovers she has the ability to traverse dream worlds, unlocking a cosmic mystery that threatens the fabric of reality.",
    rating: 4.5,
    genres: ["Sci-Fi", "Adventure", "Fantasy"],
    duration: "2h 15m",
    releaseYear: 2024,
  },
  {
    id: 2,
    title: "Cybernetic Heart",
    posterUrl: "https://picsum.photos/seed/cyber/500/750",
    description: "A rogue android with a stolen human consciousness must evade bounty hunters while searching for the meaning of her existence in the neon-drenched streets of Neo-Kyoto.",
    rating: 4.8,
    genres: ["Cyberpunk", "Action", "Thriller"],
    duration: "1h 58m",
    releaseYear: 2023,
  },
  {
    id: 3,
    title: "Forbidden Realm",
    posterUrl: "https://picsum.photos/seed/realm/500/750",
    description: "An ancient map leads a disgraced archaeologist to a hidden dimension where mythical creatures and forgotten gods vie for power.",
    rating: 4.2,
    genres: ["Fantasy", "Action", "Adventure"],
    duration: "2h 5m",
    releaseYear: 2022,
  },
  {
    id: 4,
    title: "Neon Siren",
    posterUrl: "https://picsum.photos/seed/siren/500/750",
    description: "In the rain-slicked metropolis of Aethelburg, a private investigator hunts a mysterious figure whose enchanting song leads to madness and chaos.",
    rating: 4.6,
    genres: ["Noir", "Mystery", "Sci-Fi"],
    duration: "2h 10m",
    releaseYear: 2024,
  },
  {
    id: 5,
    title: "Quantum Echo",
    posterUrl: "https://picsum.photos/seed/quantum/500/750",
    description: "A team of scientists accidentally creates a rift in spacetime, causing echoes of the past and future to bleed into the present, with catastrophic consequences.",
    rating: 4.9,
    genres: ["Sci-Fi", "Thriller", "Mind-Bender"],
    duration: "2h 25m",
    releaseYear: 2023,
  },
  {
    id: 6,
    title: "Arcane City",
    posterUrl: "https://picsum.photos/seed/arcane/500/750",
    description: "In a city powered by magic, a gifted but reckless enchanter uncovers a conspiracy that threatens to unravel the magical balance and plunge the world into darkness.",
    rating: 4.4,
    genres: ["Fantasy", "Urban", "Mystery"],
    duration: "1h 55m",
    releaseYear: 2021,
  },
    {
    id: 7,
    title: "Solaris Prime",
    posterUrl: "https://picsum.photos/seed/solaris/500/750",
    description: "The last remnants of humanity aboard a colossal starship seek a new home, but internal strife and an unknown alien presence threaten their journey.",
    rating: 4.3,
    genres: ["Sci-Fi", "Space Opera", "Drama"],
    duration: "2h 30m",
    releaseYear: 2024,
  },
  {
    id: 8,
    title: "The Gilded Automaton",
    posterUrl: "https://picsum.photos/seed/gilded/500/750",
    description: "In a steampunk Victorian era, an inventor creates a sentient automaton that becomes the key to preventing a war fueled by industrial espionage.",
    rating: 4.7,
    genres: ["Steampunk", "Adventure", "Action"],
    duration: "2h 12m",
    releaseYear: 2022,
  },
   {
    id: 9,
    title: "Abyssal Whispers",
    posterUrl: "https://picsum.photos/seed/abyssal/500/750",
    description: "A deep-sea exploration team awakens an ancient, telepathic entity that begins to turn the crew against each other in the crushing darkness of the ocean floor.",
    rating: 4.1,
    genres: ["Horror", "Sci-Fi", "Thriller"],
    duration: "1h 48m",
    releaseYear: 2023,
  },
  {
    id: 10,
    title: "Chrono Drift",
    posterUrl: "https://picsum.photos/seed/chrono/500/750",
    description: "A time-traveling agent must fix a corrupted timeline without being erased from existence herself, all while being hunted by temporal paradoxes.",
    rating: 4.6,
    genres: ["Time Travel", "Action", "Sci-Fi"],
    duration: "2h 02m",
    releaseYear: 2024,
  },
  {
    id: 11,
    title: "Valkyrie's Descent",
    posterUrl: "https://picsum.photos/seed/valkyrie/500/750",
    description: "A fallen warrior from a celestial realm is banished to a post-apocalyptic Earth, where she must lead a band of survivors against demonic invaders.",
    rating: 4.8,
    genres: ["Action", "Fantasy", "Post-Apocalyptic"],
    duration: "2h 20m",
    releaseYear: 2023,
  },
  {
    id: 12,
    title: "Eden Protocol",
    posterUrl: "https://picsum.photos/seed/eden/500/750",
    description: "In a utopian society where all emotions are suppressed, one man's illicit love affair triggers a revolution that could either liberate humanity or destroy it.",
    rating: 4.5,
    genres: ["Dystopian", "Sci-Fi", "Romance"],
    duration: "2h 18m",
    releaseYear: 2022,
  },
];

export const useMovies = (): Movie[] => {
  return mockMovies;
};
